# Generated by Django 3.1 on 2020-08-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('workers', models.CharField(max_length=30, null=True)),
                ('market', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(choices=[('Startup', 'Startup'), ('Well_established_company', 'Well_established_company'), ('Consulting_firm', 'Consulting_firm')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Linkedin', 'Linkedin'), ('Infojobs', 'Infojobs'), ('FRG', 'FRG'), ('JobFluent', 'JobFluent')], max_length=20)),
                ('emphasized', models.BooleanField(default=False)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('expired', models.BooleanField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=30, null=True)),
                ('staff_in_charge', models.CharField(blank=True, max_length=5, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('Linkedin', 'Linkedin'), ('Infojobs', 'Infojobs'), ('FRG', 'FRG'), ('JobFluent', 'JobFluent')], max_length=25)),
                ('industry', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.company')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('url', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.company')),
            ],
        ),
    ]
