# Generated by Django 3.1 on 2020-08-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_auto_20200821_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='contract_type',
            field=models.CharField(choices=[('Linkedin', 'Linkedin'), ('Infojobs', 'Infojobs'), ('FRG', 'FRG'), ('JobFluent', 'JobFluent'), ('Glassdoor', 'Glassdoor')], max_length=25),
        ),
    ]
